#[Backend]
backend = "auto"
transition_mode = "static" # The active preset is selected via the scheduler + systemd.

#[Smoothing]
smoothing = true
startup_duration = 0.3
shutdown_duration = 0.3
adaptive_interval = 1

#[Static config]
static_temp = 2600
static_gamma = 95
day_temp = 3500
night_temp = 3300
day_gamma = 90
night_gamma = 85
latitude = 41.008200
longitude = 28.978400
