# Utilities, sidepanels, and shell-adjacent windows.

windowrule=isfloating:1,width:900,height:650,appid:^(blueman-manager|nm-connection-editor|org\.gnome\.Settings|gnome-disks|pavucontrol|pwvucontrol|virt-manager)$
windowrule=isfloating:1,width:360,height:440,appid:^nm-applet$
windowrule=isfloating:1,width:960,height:720,appid:^(org\.gnome\.FileRoller|file-roller)$
windowrule=isfloating:1,width:540,height:640,appid:^(org\.gnome\.Calculator|kcalc|qalculate-gtk|org\.gnome\.Characters)$
windowrule=isfloating:1,width:700,height:450,title:^Volume Control$
windowrule=isfloating:1,width:960,height:720,appid:^(anote|org\.quickshell)$
windowrule=isfloating:1,width:540,height:1080,offsetx:95,offsety:-15,appid:^(com\.github\.hluk\.copyq|copyq|clipse|clipse-gui|wiremix|org\.pulseaudio\.pavucontrol|io\.ente\.auth)$
windowrule=isnamedscratchpad:1,width:1980,height:660,offsetx:0,offsety:-100,appid:^dropdown-terminal$
windowrule=isterm:1,appid:^(kitty|Alacritty|com\.mitchellh\.ghostty|foot)$
windowrule=noswallow:1,appid:^(mpv|org\.telegram\.desktop|ferdium|Ferdium|discord|WebCord|Signal|Slack)$
