description: Base packages (ported from nixosc)

packages:
  # Core System
  - base
  - linux-cachyos
  - linux-cachyos-headers
  - linux-firmware
  - grub
  - sudo
  - networkmanager
  - bash
  - mkinitcpio
  - paru
  - intel-ucode
  - wireplumber
  - pipewire-audio
  - bluez
  - bluez-utils

  # Build / essentials
  - base-devel
  - git
  - curl
  - wget

  # CLI file management
  - yazi
  - lf
  - eza
  - lsd
  - fd
  - ripgrep
  - fzf
  - zoxide
  - bat
  - duf
  - ncdu
  - trash-cli
  - unzip
  - 7zip
  - atool
  - rsync
  - lftp
  - tree
  - plocate

  # Dev tools
  - gcc
  - make
  - jq
  - yq
  - go
  - python
  - python-pip
  - python-pipx
  - ipython
  - lua-language-server
  - stylua
  - shellcheck
  - shfmt
  - podman
  - podman-compose

  # Terminals / UX
  - tmux
  - wezterm
  - kitty
  - starship
  - fastfetch
  - neofetch
  - htop
  - btop
  - procs
  - inxi
  - tealdeer
  - psmisc

  # Wayland tooling
  - wl-clipboard
  - wtype
  - libnotify
  - xdg-utils
  - dbus

  # Network
  - aria2
  - bind
  - nmap
  - mtr
  - iputils
  - fping
  - iftop
  - iptraf-ng
  - speedtest-cli
  - iperf3
  - tcpdump
  - openssh
  - assh-bin

  # VPN
  - openvpn
  - openconnect
  - openfortivpn
  - wireguard-tools

  # Media tooling
  - ffmpeg
  - imagemagick
  - yt-dlp

  # Desktop utilities
  - nemo
  - grim
  - slurp
  - wf-recorder
  - swappy
  - brightnessctl
  - rofi
  - tigervnc

  # Documents
  - zathura
  - evince
  - poppler
  # pdftk pulls java-runtime-headless; pick a concrete provider to avoid pacman prompts
  - jre-openjdk-headless
  - pdftk
  - qalculate-gtk

  # Security
  - keepassxc
  - age
  - sops
  - pwgen

  # Flatpak (optional but matches nixosc)
  - flatpak
