#!/usr/bin/env bash
set -euo pipefail

# This script requires root to update system GRUB
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (via dcli sync with sudo)"
    exit 1
fi

SECONDARY_ROOT="/cachy/@"
CURRENT_BOOT_GRUB="/boot/grub"
SECONDARY_BOOT_GRUB="$SECONDARY_ROOT/boot/grub"
ROG_EFI_UUID="${OSC_GRUB_ROG_EFI_UUID:-6880-73B3}"
FALLBACK_EFI_UUID="${OSC_GRUB_FALLBACK_EFI_UUID:-9287-D3F5}"

declare -a INSTALL_ROOTS=()
declare -a INSTALL_DEVS=()
declare -a INSTALL_UUIDS=()

cleanup_generated_custom_cfg() {
    local target_dir="$1"
    local cfg="$target_dir/custom.cfg"

    # Avoid duplicate menu entries: 40_custom is already compiled into grub.cfg.
    # If an older generated custom.cfg exists with the same managed block,
    # remove it so 41_custom doesn't source duplicates.
    if [ -f "$cfg" ] && grep -q "Cross-install GRUB jump entries for dual CachyOS setup." "$cfg"; then
        rm -f "$cfg"
        echo "Removed generated duplicate: $cfg"
    fi
}

mount_source_for_path() {
    local path="$1"
    findmnt -no SOURCE -T "$path" 2>/dev/null || true
}

mount_uuid_for_path() {
    local path="$1"
    local source=""
    local uuid=""

    source="$(mount_source_for_path "$path")"
    uuid="$(findmnt -no UUID -T "$path" 2>/dev/null || true)"

    if [ -z "$uuid" ] && [ -n "$source" ]; then
        uuid="$(blkid -s UUID -o value "$source" 2>/dev/null || true)"
    fi

    printf '%s\n' "$uuid"
}

register_install() {
    local root_path="$1"
    local source=""
    local uuid=""
    local dev=""
    local idx=""

    [ -d "$root_path" ] || return 0

    source="$(mount_source_for_path "$root_path")"
    uuid="$(mount_uuid_for_path "$root_path")"
    [ -n "$uuid" ] || return 0

    for idx in "${!INSTALL_UUIDS[@]}"; do
        if [ "${INSTALL_UUIDS[$idx]}" = "$uuid" ]; then
            return 0
        fi
    done

    dev="${source#/dev/}"
    dev="${dev%%[*}"
    [ -n "$dev" ] || dev="unknown"

    INSTALL_ROOTS+=("$root_path")
    INSTALL_DEVS+=("$dev")
    INSTALL_UUIDS+=("$uuid")
}

build_cross_entries_for_target() {
    local target_uuid="$1"
    local idx=""
    local added=0
    local dev=""
    local uuid=""

    for idx in "${!INSTALL_UUIDS[@]}"; do
        dev="${INSTALL_DEVS[$idx]}"
        uuid="${INSTALL_UUIDS[$idx]}"

        if [ "$uuid" = "$target_uuid" ]; then
            continue
        fi

        cat <<EOF
    menuentry "Other CachyOS (${dev}, UUID ${uuid})" {
        insmod part_gpt
        insmod btrfs
        search --no-floppy --fs-uuid --set=root ${uuid}
        if [ -f /@/boot/grub/grub.cfg ]; then
            configfile /@/boot/grub/grub.cfg
        elif [ -f /boot/grub/grub.cfg ]; then
            configfile /boot/grub/grub.cfg
        else
            echo "grub.cfg not found on ${dev}"
            sleep 3
        fi
    }

EOF
        added=1
    done

    if [ "$added" -eq 0 ]; then
        cat <<'EOF'
    menuentry "No other CachyOS install detected" {
        echo "No additional CachyOS btrfs root found."
        sleep 2
    }

EOF
    fi
}

render_custom_for_target() {
    local target_uuid="$1"

    cat <<'EOF'
#!/bin/sh
exec tail -n +3 $0
# Cross-install GRUB jump entries for dual CachyOS setup.
# This file is autogenerated by modules/grub/scripts/install.sh

submenu "CachyOS installs (cross-GRUB)" {
EOF

    build_cross_entries_for_target "$target_uuid"

    cat <<EOF
    menuentry "CachyOS Rog (sda1, EFI UUID ${ROG_EFI_UUID})" {
        insmod part_gpt
        insmod fat
        search --no-floppy --fs-uuid --set=root ${ROG_EFI_UUID}
        chainloader /EFI/cachyos/grubx64.efi
    }

    menuentry "CachyOS EFI fallback (ESP ${FALLBACK_EFI_UUID})" {
        insmod part_gpt
        insmod fat
        search --no-floppy --fs-uuid --set=root ${FALLBACK_EFI_UUID}
        chainloader /EFI/cachyos/grubx64.efi
    }
}
EOF
}

install_custom_for_root() {
    local root_path="$1"
    local target_etc_grub="$2"
    local target_boot_grub="$3"
    local target_uuid=""
    local tmp_custom=""

    target_uuid="$(mount_uuid_for_path "$root_path")"
    [ -n "$target_uuid" ] || return 1

    tmp_custom="$(mktemp)"
    render_custom_for_target "$target_uuid" >"$tmp_custom"
    install -m 755 "$tmp_custom" "${target_etc_grub}/40_custom"
    rm -f "$tmp_custom"

    cleanup_generated_custom_cfg "$target_boot_grub"
}

register_install "/"
register_install "$SECONDARY_ROOT"

if [ "${#INSTALL_UUIDS[@]}" -eq 0 ]; then
    echo "No CachyOS btrfs roots detected from mounts; aborting." >&2
    exit 1
fi

echo "Installing custom GRUB entry for current system..."
install_custom_for_root "/" "/etc/grub.d" "$CURRENT_BOOT_GRUB"

echo "Updating GRUB configuration..."
if command -v update-grub >/dev/null 2>&1; then
    update-grub
else
    grub-mkconfig -o /boot/grub/grub.cfg
fi

if [ -d "$SECONDARY_ROOT/etc/grub.d" ] && [ -n "$(mount_uuid_for_path "$SECONDARY_ROOT")" ]; then
    echo "Syncing custom GRUB entry to secondary CachyOS root: $SECONDARY_ROOT"
    install_custom_for_root "$SECONDARY_ROOT" "$SECONDARY_ROOT/etc/grub.d" "$SECONDARY_BOOT_GRUB" || true
fi

echo "GRUB update complete."
