max-gamma = 150

profile {
    time = 07:30
    identity = true
}

profile {
    time = 20:00
    temperature = 2800
    gamma = 1.0
}

profile {
    time = 22:00
    temperature = 2600
    gamma = 0.95
}

profile {
    time = 00:00
    temperature = 2500
    gamma = 0.90
}
