max-gamma = 150

profile {
    time = 07:30
    temperature = 2700
    gamma = 0.97
}

profile {
    time = 10:00
    temperature = 2650
    gamma = 0.96
}

profile {
    time = 13:00
    temperature = 2600
    gamma = 0.95
}

profile {
    time = 17:00
    temperature = 2500
    gamma = 0.94
}

profile {
    time = 19:00
    temperature = 2400
    gamma = 0.92
}

profile {
    time = 21:00
    temperature = 2300
    gamma = 0.90
}

profile {
    time = 22:30
    temperature = 2200
    gamma = 0.88
}

profile {
    time = 00:00
    temperature = 2100
    gamma = 0.86
}

profile {
    time = 02:00
    temperature = 2000
    gamma = 0.84
}

profile {
    time = 04:00
    temperature = 1950
    gamma = 0.82
}
