max-gamma = 150

profile {
    time = 07:30
    temperature = 3000
    gamma = 0.95
}

profile {
    time = 18:30
    temperature = 2900
    gamma = 0.92
}

profile {
    time = 20:30
    temperature = 2800
    gamma = 0.90
}

profile {
    time = 22:00
    temperature = 2600
    gamma = 0.88
}

profile {
    time = 23:30
    temperature = 2500
    gamma = 0.86
}

profile {
    time = 01:30
    temperature = 2400
    gamma = 0.84
}

profile {
    time = 03:30
    temperature = 2300
    gamma = 0.80
}
