host: hay
description: CachyOS setup (ported from nixosc via dcli)

# Ordered list (requires module_processing: sequential)
enabled_modules:
  # --- Core ---
  - base
  - xdg-dirs
  - xdg-mimes
  - scripts
  - packages
  # - packages # Meta-module, usually not needed if others are enabled

  # --- Shell ---
  - zsh
  - bash
  - starship

  # --- CLI Tools ---
  - git
  - command-not-found
  - bat
  - btop
  - fastfetch
  - yazi
  - lazygit
  - rsync
  # - gnupg
  # - search

  # --- Editors ---
  - nvim

  # --- Terminals ---
  - kitty
  - wezterm
  # - alacritty
  # - foot
  # - ghostty

  # --- Desktop Environment (WM/Compositor) ---
  - niri
  # - nirius
  - hyprland
  - sessions
  # - sway
  # - gnome
  # - cosmic
  # - xserver

  # --- Desktop Components & Theming ---
  - gtk
  - qt
  - dms
  - dms-greeter
  # - mako
  - rofi
  # - walker
  - xdg-portal
  - fusuma
  # - hyprpanel
  # - catppuccin

  # --- Media ---
  - mpv
  - mpd
  - rmpc
  - cava
  - ytdlp
  # - vlc
  - radio
  # - audacious
  # - subliminal

  # --- Network & Connectivity ---
  - anydesk
  - connect # KDE Connect
  #- blue # Gammastep/Sunset
  - bt # Bluetooth
  # - sunsetr

  # --- Browsers ---
  - brave
  # - chrome
  # - firefox

  # --- Applications ---
  # - obsidian
  - webcord
  - flatpak
  - transmission
  # - elektron
  # - nemo
  # - program

  # --- AI ---
  - ai
  # - ollama (merged into ai)

  # --- System & Utility ---
  - clipse
  - sesh
  - stasis
  - tmux
  - user-services
  - admin
  - logind
  - kernel
  - pacman
  - firewall
  - fail2ban
  - hblock
  - tcp
  # - grub
  # - cliphist
  # - copyq

# Settings
module_processing: sequential
flatpak_scope: user
# dcli will auto-detect if omitted (prefers paru → yay)
aur_helper: paru

auto_prune: false

services:
  enabled:
    - bluetooth
    - NetworkManager

config_backups:
  enabled: true
  max_backups: 5

# System backups (Timeshift/Snapper)
system_backups:
  enabled: true
  backup_on_sync: true
  backup_on_update: true
  tool: snapper
  snapper_config: root
  max_backups: 5

# Default applications configuration
default_apps:
  scope: user # "user" or "system"

  # Core defaults (category-level)
  browser: brave-browser.desktop
  text_editor: kitty-nvim.desktop
  file_manager: nemo.desktop
  terminal: kitty.desktop
  office: libreoffice-startcenter.desktop
  pdf: org.gnome.Evince.desktop
  archive: org.gnome.FileRoller.desktop
  video: mpv.desktop
  music: mpv.desktop
  image: imv-dir.desktop
  discord: webcord.desktop
  mpv_handler: open-in-mpv.desktop

  # Custom MIME types (explicit mapping)
  mime_types:
    # Browser / URL handlers
    text/html: brave-browser.desktop
    application/xhtml+xml: brave-browser.desktop
    x-scheme-handler/http: brave-browser.desktop
    x-scheme-handler/https: brave-browser.desktop
    x-scheme-handler/about: brave-browser.desktop
    x-scheme-handler/unknown: brave-browser.desktop

    # Text
    text/plain: kitty-nvim.desktop

    # Images
    image/bmp: imv-dir.desktop
    image/gif: imv-dir.desktop
    image/jpeg: imv-dir.desktop
    image/jpg: imv-dir.desktop
    image/png: imv-dir.desktop
    image/svg+xml: imv-dir.desktop
    image/tiff: imv-dir.desktop
    image/vnd.microsoft.icon: imv-dir.desktop
    image/webp: imv-dir.desktop

    # Audio
    audio/aac: mpv.desktop
    audio/mpeg: mpv.desktop
    audio/ogg: mpv.desktop
    audio/opus: mpv.desktop
    audio/wav: mpv.desktop
    audio/webm: mpv.desktop
    audio/x-matroska: mpv.desktop

    # Video
    video/mp2t: mpv.desktop
    video/mp4: mpv.desktop
    video/mpeg: mpv.desktop
    video/ogg: mpv.desktop
    video/webm: mpv.desktop
    video/x-flv: mpv.desktop
    video/x-matroska: mpv.desktop
    video/x-msvideo: mpv.desktop

    # Directory
    inode/directory: nemo.desktop

    # Office docs
    application/vnd.oasis.opendocument.text: libreoffice-writer.desktop
    application/vnd.oasis.opendocument.spreadsheet: libreoffice-calc.desktop
    application/vnd.oasis.opendocument.presentation: libreoffice-impress.desktop
    application/vnd.openxmlformats-officedocument.wordprocessingml.document: libreoffice-writer.desktop
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: libreoffice-calc.desktop
    application/vnd.openxmlformats-officedocument.presentationml.presentation: libreoffice-impress.desktop
    application/msword: libreoffice-writer.desktop
    application/vnd.ms-excel: libreoffice-calc.desktop
    application/vnd.ms-powerpoint: libreoffice-impress.desktop
    application/rtf: libreoffice-writer.desktop

    # PDF
    application/pdf: org.gnome.Evince.desktop

    # Archives
    application/zip: org.gnome.FileRoller.desktop
    application/rar: org.gnome.FileRoller.desktop
    application/7z: org.gnome.FileRoller.desktop
    application/*tar: org.gnome.FileRoller.desktop

    # Custom scheme handlers
    x-scheme-handler/discord: webcord.desktop
    x-scheme-handler/mpv: open-in-mpv.desktop
