# Base MangoWM behavior shared across all monitor profiles.

allow_tearing=2
focus_on_activate=1
focus_cross_monitor=0
focus_cross_tag=0
sloppyfocus=0
warpcursor=0
cursor_hide_timeout=3
drag_tile_to_tile=1
drag_corner=4
enable_floating_snap=1
snap_distance=30
enable_hotarea=1
hotarea_size=10
hotarea_corner=3
ov_tab_mode=0
view_current_to_back=1
axis_bind_apply_timeout=100
axis_scroll_factor=1.25
no_border_when_single=0
idleinhibit_ignore_visible=0
scratchpad_cross_monitor=1
circle_layout=scroller,tile,center_tile,monocle,vertical_grid
