# Layout model biased toward Mango's scroller mode to approximate Niri's feel.

scroller_structs=20
scroller_default_proportion=0.786
scroller_focus_center=1
scroller_prefer_center=0
edge_scroller_pointer_focus=1
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.500,0.618,0.786,0.900,1.000

new_is_master=0
default_mfact=0.55
default_nmaster=1
smartgaps=0

overviewgappi=6
overviewgappo=30
