# Layout model biased toward Mango's scroller mode to approximate Niri's feel.

scroller_structs=24
scroller_default_proportion=0.800
scroller_ignore_proportion_single=0
scroller_focus_center=1
scroller_prefer_center=1
scroller_prefer_overspread=0
edge_scroller_pointer_focus=1
scroller_default_proportion_single=0.800
scroller_proportion_preset=1.000,0.800,0.618,0.500

new_is_master=0
default_mfact=0.55
default_nmaster=1
smartgaps=0

overviewgappi=12
overviewgappo=60
