# Mouse, wheel, and touchpad gesture bindings.

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=NONE,btn_middle,togglemaximizescreen,0

axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

gesturebind=NONE,left,3,focusdir,left
gesturebind=NONE,right,3,focusdir,right
gesturebind=NONE,up,3,focusdir,up
gesturebind=NONE,down,3,focusdir,down
gesturebind=NONE,right,4,tagmon,up,1
gesturebind=NONE,left,4,tagmon,down,1
gesturebind=NONE,up,4,toggleoverview
gesturebind=NONE,down,4,toggleoverview
