interval:
  pinch: 1.0
  swipe: 0.7

threshold:
  pinch: 0.3
  swipe: 0.8

pinch:
  3:
    in:
      command: "fusuma-fullscreen in"
    out:
      command: "fusuma-fullscreen out"

swipe:
  3:
    left:
      command: "fusuma-swipe 3 left"
      threshold: 0.6
    right:
      command: "fusuma-swipe 3 right"
      threshold: 0.6
    up:
      command: "fusuma-swipe 3 up"
      threshold: 0.6
    down:
      command: "fusuma-swipe 3 down"
      threshold: 0.6

  4:
    up:
      command: "fusuma-swipe 4 up"
    down:
      command: "fusuma-swipe 4 down"
    left:
      command: "fusuma-swipe 4 left"
    right:
      command: "fusuma-swipe 4 right"
