# Niri Session Environment (Systemd managed)
# Applied at login before portal services start.

XDG_CURRENT_DESKTOP=niri
XDG_SESSION_TYPE=wayland
XDG_SESSION_DESKTOP=niri
DESKTOP_SESSION=niri

# Toolkit integration
GTK_THEME=catppuccin-mocha-mauve-standard+default
XCURSOR_THEME=catppuccin-mocha-dark-cursors
XCURSOR_SIZE=24
XDG_ICON_THEME=kora

QT_QPA_PLATFORM="wayland;xcb"
QT_QPA_PLATFORMTHEME=gtk3
QT_STYLE_OVERRIDE=kvantum
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
ELECTRON_OZONE_PLATFORM_HINT=auto
MOZ_ENABLE_WAYLAND=1

# Use Portal for File Pickers (Crucial for Tiling WMs)
GTK_USE_PORTAL=1

# Visibility for Flatpak and Native apps
XDG_DATA_DIRS=${HOME}/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
