# Core window rules

windowrule {
  name=suppress-maximize-events
  match:class=.*
  suppress_event=maximize
}

windowrule {
  name=fix-xwayland-drags
  match:class=^$
  match:float=true
  match:fullscreen=false
  match:pin=false
  match:title=^$
  match:xwayland=true
  no_focus=true
}

windowrule {
  name=xwaylandvideobridge-hidden
  float=true
  match:class=^(xwaylandvideobridge)$
  move=0 0
  no_focus=true
  opacity=0.0 override 0.0 override
  size=1 1
}

windowrule {
  name=context-menu-noshadow
  match:class=^()$
  match:title=^()$
  no_shadow=true
}

windowrule {
  name=context-menu-noblur
  match:class=^()$
  match:title=^()$
  no_blur=true
}

windowrule {
  name=portal-dialogs
  center=true
  float=true
  match:class=^(xdg-desktop-portal-(gtk|gnome|hyprland))$
}

windowrule {
  name=maximized-window-no-decos
  match:float=false
  match:fullscreen_state_internal=1
  no_shadow=true
  rounding=0
}

windowrule {
  name=mpv-float
  float=true
  match:class=^(mpv)$
  move=(monitor_w-640-32) 96
  opacity=1.0 override 1.0 override
  persistent_size=true
  size=640 360
}
