# Layout behavior and grouping policy

windowrule {
  name=group-default-barred
  match:class=.*
  group=barred
}

windowrule {
  name=terminal-docs-auto-group
  match:class=^(Tmux|TmuxKenp|evince)$
  group=override set
}

windowrule {
  name=kitty-tmux-auto-group
  match:class=^(kitty)$
  match:title=^(Tmux)$
  group=override set
}

windowrule {
  name=browser-chat-group-deny
  match:class=^(Brave-browser|firefox|google-chrome|Ferdium|ferdium|org\.telegram\.desktop|discord|Discord|WebCord|Spotify|spotify|com\.spotify\.Client|vlc|Vncviewer|remote-viewer|qemu-system-x86_64|qemu)$
  group=override deny
}
