# Theme overrides and opacity exceptions

windowrule {
  name=floating-border
  border_size=$themeBorderSize
  match:float=true
  match:workspace=w[v2-99]s[false]
}

windowrule {
  name=floating-rounding
  match:float=true
  match:workspace=w[v2-99]s[false]
  rounding=$themeFloatingRounding
}

windowrule {
  name=notes-float
  center=true
  float=true
  match:class=^(notes)$
  persistent_size=true
  size=(monitor_w*0.70) (monitor_h*0.50)
}

windowrule {
  name=anote-float
  center=true
  float=true
  match:class=^(anote)$
  persistent_size=true
  size=1152 864
}

windowrule {
  name=clipb-float
  center=true
  float=true
  match:class=^(clipb)$
  persistent_size=true
  size=1536 864
}

windowrule {
  name=clip-preview-float
  center=true
  float=true
  match:class=^(clip-preview)$
  opacity=0.98 0.98
  persistent_size=true
  size=900 700
}

windowrule {
  name=kitty-opacity
  match:class=^(kitty)$
  opacity=1.0 override 1.0 override
}

windowrule {
  name=brave-opacity
  match:class=^(Brave-browser)$
  opacity=1.0 override 1.0 override
}

windowrule {
  name=kenp-opacity
  match:class=^(Kenp)$
  opacity=1.0 override 1.0 override
}
