#!/bin/sh
exec tail -n +3 $0
# Custom GRUB entries
# - Keep entries deterministic (UUID + chainloader path)
# - Avoid stale ESP references

# ----------------------------------------------------------------------
# CachyOS installed on SATA disk (sda) - chainload its own GRUB
# Verified on /dev/sda1 (UUID 6880-73B3):
#   /EFI/cachyos/grubx64.efi
# ----------------------------------------------------------------------
menuentry "CachyOS Rog (sda1 - GRUB chainload)" {
    insmod part_gpt
    insmod fat
    search --no-floppy --fs-uuid --set=root 6880-73B3
    chainloader /EFI/cachyos/grubx64.efi
}

# ----------------------------------------------------------------------
# Current system CachyOS EFI chainload entry
# EFI UUID (vfat): 9287-D3F5
# ----------------------------------------------------------------------
menuentry "CachyOS Lenovo (EFI - GRUB chainload)" {
    insmod part_gpt
    insmod fat
    search --no-floppy --fs-uuid --set=root 9287-D3F5
    chainloader /EFI/cachyos/grubx64.efi
}

# ----------------------------------------------------------------------
# Second CachyOS on /dev/nvme0n1p1 (btrfs UUID 6784b6e4-7e6e-4662-9554-7bb313b427ee)
# Root subvolume: @
# Boot files available at /@/boot/*
# ----------------------------------------------------------------------
menuentry "CachyOS NVMe0 (linux-cachyos-bore)" {
    insmod part_gpt
    insmod btrfs
    search --no-floppy --fs-uuid --set=root 6784b6e4-7e6e-4662-9554-7bb313b427ee
    linux /@/boot/vmlinuz-linux-cachyos-bore root=UUID=6784b6e4-7e6e-4662-9554-7bb313b427ee rw rootflags=subvol=@ nowatchdog nvme_load=YES zswap.enabled=0 splash loglevel=3 intel_pstate=active intel_idle.max_cstate=7 processor.ignore_ppc=1 i915.enable_guc=3 i915.enable_fbc=1 i915.enable_dc=2 i915.enable_psr=1 i915.fastboot=1 mem_sleep_default=s2idle
    initrd /@/boot/intel-ucode.img /@/boot/initramfs-linux-cachyos-bore.img
}

menuentry "CachyOS NVMe0 (linux-cachyos)" {
    insmod part_gpt
    insmod btrfs
    search --no-floppy --fs-uuid --set=root 6784b6e4-7e6e-4662-9554-7bb313b427ee
    linux /@/boot/vmlinuz-linux-cachyos root=UUID=6784b6e4-7e6e-4662-9554-7bb313b427ee rw rootflags=subvol=@ nowatchdog nvme_load=YES zswap.enabled=0 splash loglevel=3 intel_pstate=active intel_idle.max_cstate=7 processor.ignore_ppc=1 i915.enable_guc=3 i915.enable_fbc=1 i915.enable_dc=2 i915.enable_psr=1 i915.fastboot=1 mem_sleep_default=s2idle
    initrd /@/boot/intel-ucode.img /@/boot/initramfs-linux-cachyos.img
}
