[colors]
background = '#24273a'
foreground = '#cad3f5'

cursor_bg = '#c6a0f6'
cursor_fg = '#24273a'
cursor_border = '#c6a0f6'

selection_bg = '#532f7d'
selection_fg = '#cad3f5'

ansi = ['#1e2030', '#ff728c', '#7bf696', '#ffdb72', '#b287e9', '#492871', '#c6a0f6', '#f6efff']
brights = ['#99939f', '#ff9fb1', '#a5ffb9', '#ffe8a5', '#d4b3ff', '#dcc0ff', '#e8d6ff', '#fbf8ff']
