# Blocky configuration
# https://0xerr0r.github.io/blocky/latest/

ports:
  dns: 53
  http: 4000

log:
  level: info

upstreams:
  # Don't block service start if upstreams aren't reachable yet.
  init:
    strategy: fast
  # Pick the fastest upstreams per query.
  strategy: parallel_best
  timeout: 2s
  groups:
    default:
      - 1.1.1.1
      - 9.9.9.9

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/blocklistproject/Lists/master/ads.txt

  clientGroupsBlock:
    default:
      - ads

  loading:
    refreshPeriod: 24h
    strategy: fast
