# Key bindings index

source=~/.config/hypr/conf.d/binds/10-navigation.conf
source=~/.config/hypr/conf.d/binds/20-shell-session.conf
source=~/.config/hypr/conf.d/binds/30-apps.conf
source=~/.config/hypr/conf.d/binds/40-workspaces.conf
source=~/.config/hypr/conf.d/binds/50-monitors-hardware.conf
