# Generic workspace styling rules

workspace=w[tv1], gapsout:6, gapsin:6, rounding:0, shadow:0
workspace=f[1], gapsout:0, gapsin:0, rounding:0, shadow:0
workspace=w[v2-99]s[false], bordersize:3, rounding:true
workspace=special:dropdown, gapsout:0, gapsin:0, bordersize:0, rounding:0, shadow:0
workspace=special:scratchpad, gapsout:0, gapsin:0, bordersize:0, rounding:0, shadow:0
