#[Backend]
backend = "auto"
transition_mode = "static"

#[Smoothing]
smoothing = true
startup_duration = 0.3
shutdown_duration = 0.3
adaptive_interval = 1

#[Static config]
static_temp = 2100
static_gamma = 89
