#[Backend]
backend = "auto"
transition_mode = "static"

#[Smoothing]
smoothing = true
startup_duration = 0.3
shutdown_duration = 0.3
adaptive_interval = 1

#[Time-based config]
night_temp = 2100
day_temp = 2100
night_gamma = 86
day_gamma = 86
update_interval = 60

#[Static config]
static_temp = 2100
static_gamma = 86

#[Manual transitions]
sunset = "00:00:00"
sunrise = "00:00:00"
transition_duration = 5

#[Geolocation]
latitude = 41.008200
longitude = 28.978400
