# Lock-screen config — written by Settings → Lock.
background = color
background_color = #1E1E2E
background_image = ~/Pictures/wallpapers/others/38.jpg
show_avatar = true
show_greeting = true
show_date = true
show_battery = true
show_layout = true
show_notifications = true
show_weather = true
show_media = true
