#!/usr/bin/env bash
# Profile: brave-kenp
# Generated by Semsumo v8.0.0 (Unified Edition)
set -e

readonly APP_TIMEOUT=4
readonly CHECK_INTERVAL=1
readonly WORKSPACE=1
readonly VPN_MODE="secure"
readonly FULLSCREEN=false
readonly WAIT_TIME=2
readonly COMMAND="profile_brave"
readonly ARGS_STR="Kenp --separate --restore-last-session"
readonly STATE_DIR="/run/user/1000/semsumo"

# Detect window manager
if command -v hyprctl &>/dev/null && hyprctl version &>/dev/null; then
    WM_TYPE="hyprland"
elif command -v niri &>/dev/null && [[ "$XDG_CURRENT_DESKTOP" == "niri" ]]; then
    WM_TYPE="niri"
else
    WM_TYPE="generic"
fi

echo "Initializing brave-kenp on $WM_TYPE..."

APP_ARGS=()
if [[ -n "$ARGS_STR" ]]; then
    read -r -a APP_ARGS <<<"$ARGS_STR"
fi
if [[ $# -gt 0 ]]; then
    APP_ARGS+=("$@")
fi

# Switch to workspace
if [[ "$WORKSPACE" != "0" ]]; then
    case "$WM_TYPE" in
    hyprland)
        if command -v hyprctl >/dev/null 2>&1; then
            CURRENT=$(hyprctl activeworkspace -j | grep -o '"id": [0-9]*' | grep -o '[0-9]*' || echo "")
            if [[ "$CURRENT" != "$WORKSPACE" ]]; then
                echo "Switching to workspace $WORKSPACE..."
                hyprctl dispatch workspace "$WORKSPACE"
                sleep 1
            fi
        fi
        ;;
    niri)
        if command -v niri >/dev/null 2>&1; then
            echo "Switching to workspace $WORKSPACE..."
            if [[ -x "$HOME/.local/bin/niri-osc" ]]; then
                "$HOME/.local/bin/niri-osc" flow legacy -wn "$WORKSPACE"
            else
                niri msg action focus-workspace "$WORKSPACE"
            fi
            sleep 1
        fi
        ;;
    *)
        if command -v wmctrl >/dev/null 2>&1; then
            TARGET=$((WORKSPACE - 1))
            echo "Switching to workspace $WORKSPACE..."
            wmctrl -s "$TARGET"
            sleep 1
        fi
        ;;
    esac
fi

echo "Starting application..."
echo "COMMAND: $COMMAND ${APP_ARGS[*]}"
echo "VPN MODE: $VPN_MODE"

# Start application with VPN mode
case "$VPN_MODE" in
    bypass)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            if command -v mullvad-exclude >/dev/null 2>&1; then
                echo "Starting with VPN bypass"
                mullvad-exclude "$COMMAND" "${APP_ARGS[@]}" &
            else
                echo "WARNING: mullvad-exclude not found"
                "$COMMAND" "${APP_ARGS[@]}" &
            fi
        else
            echo "VPN not connected"
            "$COMMAND" "${APP_ARGS[@]}" &
        fi
        ;;
    secure|*)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            echo "Starting with VPN protection"
        else
            echo "WARNING: VPN not connected!"
        fi
        "$COMMAND" "${APP_ARGS[@]}" &
        ;;
esac

APP_PID=$!
mkdir -p "$STATE_DIR"
echo "$APP_PID" > "$STATE_DIR/brave-kenp.pid"
echo "$COMMAND" > "$STATE_DIR/brave-kenp.cmd"
echo "Application started (PID: $APP_PID)"

# Window verification (Hyprland only)
if [[ "$WORKSPACE" != "0" && "$WM_TYPE" == "hyprland" ]] && command -v hyprctl >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
    echo "Verifying window on workspace $WORKSPACE..."
    ELAPSED=0
    CLASS_PATTERN="Kenp"
    
    while [[ $ELAPSED -lt $APP_TIMEOUT ]]; do
        if hyprctl clients -j 2>/dev/null | jq -e ".[] | select(.workspace.id == $WORKSPACE and (.class | test(\"$CLASS_PATTERN\"; \"i\")))" >/dev/null 2>&1; then
            echo "Window verified after ${ELAPSED}s"
            break
        fi
        sleep $CHECK_INTERVAL
        ((ELAPSED += CHECK_INTERVAL))
        if ((ELAPSED % 3 == 0)); then
            echo "Waiting... (${ELAPSED}/${APP_TIMEOUT}s)"
        fi
    done
    
    [[ $ELAPSED -ge $APP_TIMEOUT ]] && echo "WARNING: Timeout after ${APP_TIMEOUT}s"
else
    sleep $WAIT_TIME
fi

# Make fullscreen if needed
if [[ "$FULLSCREEN" == "true" ]]; then
    sleep $WAIT_TIME
    case "$WM_TYPE" in
    hyprland)
        command -v hyprctl >/dev/null 2>&1 && hyprctl dispatch fullscreen 1
        ;;
    niri)
        command -v niri >/dev/null 2>&1 && niri msg action fullscreen-window
        ;;
    esac
fi

echo "brave-kenp initialization complete"
exit 0