#!/usr/bin/env bash
# Profile: helium-compecta
# Generated by Semsumo v8.0.0 (Unified Edition)
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMON_HELPER="$HOME/.local/bin/wayland-session-common"
[[ -r "${COMMON_HELPER}.sh" ]] && COMMON_HELPER="${COMMON_HELPER}.sh"
[[ -r "${COMMON_HELPER}" ]] || COMMON_HELPER="${SCRIPT_DIR}/../bin/wayland-session-common.sh"
[[ -r "${COMMON_HELPER}" ]] || COMMON_HELPER="${SCRIPT_DIR}/../bin/wayland-session-common"
if [[ -r "${COMMON_HELPER}" ]]; then
    # shellcheck source=/dev/null
    source "${COMMON_HELPER}"
    session_common_backfill_visual_env
fi

export PATH="$HOME/.local/bin:$HOME/bin:/usr/local/bin:/usr/bin:/bin:${PATH:-}"

readonly APP_TIMEOUT=4
readonly CHECK_INTERVAL=1
readonly WORKSPACE=4
readonly VPN_MODE="secure"
readonly FULLSCREEN=false
readonly WAIT_TIME=2
readonly COMMAND="profile_helium"
readonly ARGS_STR="compecta --separate --restore-last-session"
readonly STATE_DIR="/run/user/1000/semsumo"

# Detect window manager (margo or generic Wayland)
if [[ "${XDG_CURRENT_DESKTOP:-}" == *margo* ]] || (command -v mctl &>/dev/null && mctl status &>/dev/null); then
    WM_TYPE="margo"
else
    WM_TYPE="wayland"
fi

echo "Initializing helium-compecta on $WM_TYPE..."

APP_ARGS=()
if [[ -n "$ARGS_STR" ]]; then
    read -r -a APP_ARGS <<<"$ARGS_STR"
fi
if [[ $# -gt 0 ]]; then
    APP_ARGS+=("$@")
fi

# Switch to workspace
if [[ "$WORKSPACE" != "0" ]]; then
    case "$WM_TYPE" in
    margo)
        if command -v mctl >/dev/null 2>&1; then
            echo "Switching to workspace $WORKSPACE..."
            mctl tags $((1 << (WORKSPACE - 1))) || echo "WARNING: Margo workspace switch failed"
            sleep 1
        fi
        ;;
    wayland|*)
        echo "Skipping workspace switch on generic Wayland session..."
        ;;
    esac
fi

echo "Starting application..."
echo "COMMAND: $COMMAND ${APP_ARGS[*]}"
echo "VPN MODE: $VPN_MODE"

# Start application with VPN mode
case "$VPN_MODE" in
    bypass)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            if command -v mullvad-exclude >/dev/null 2>&1; then
                echo "Starting with VPN bypass"
                mullvad-exclude "$COMMAND" "${APP_ARGS[@]}" &
            else
                echo "WARNING: mullvad-exclude not found"
                "$COMMAND" "${APP_ARGS[@]}" &
            fi
        else
            echo "VPN not connected"
            "$COMMAND" "${APP_ARGS[@]}" &
        fi
        ;;
    secure|*)
        if command -v mullvad >/dev/null 2>&1 && mullvad status 2>/dev/null | grep -q "Connected"; then
            echo "Starting with VPN protection"
        else
            echo "WARNING: VPN not connected!"
        fi
        "$COMMAND" "${APP_ARGS[@]}" &
        ;;
esac

APP_PID=$!
mkdir -p "$STATE_DIR"
echo "$APP_PID" > "$STATE_DIR/helium-compecta.pid"
echo "$COMMAND" > "$STATE_DIR/helium-compecta.cmd"
echo "Application started (PID: $APP_PID)"

# No window verification on margo / generic Wayland; just wait for the app to
# settle.
# TODO: margo equivalent (per-window verification via mctl, if available)
sleep $WAIT_TIME

# Make fullscreen if needed
if [[ "$FULLSCREEN" == "true" ]]; then
    # No margo / generic Wayland fullscreen automation; toggle manually (F11).
    # TODO: margo equivalent (fullscreen dispatch via mctl, if available)
    sleep $WAIT_TIME
fi

echo "helium-compecta initialization complete"
exit 0