# Navigation and layout bindings

bind=$mainMod, left, exec, ~/.local/bin/hypr-scroll focus l
bind=$mainMod, right, exec, ~/.local/bin/hypr-scroll focus r
bind=$mainMod, up, workspace, e-1
bind=$mainMod, down, workspace, e+1
bind=$mainMod, h, exec, ~/.local/bin/hypr-scroll focus l
bind=$mainMod, l, exec, ~/.local/bin/hypr-scroll focus r
bind=$mainMod, k, workspace, e-1
bind=$mainMod, j, workspace, e+1
bind=$mainMod CTRL, K, movefocus, u
bind=$mainMod CTRL, J, movefocus, d
bind=$mainMod SHIFT, left, exec, ~/.local/bin/hypr-scroll swapcol l
bind=$mainMod SHIFT, right, exec, ~/.local/bin/hypr-scroll swapcol r
bind=$mainMod SHIFT, up, exec, ~/.local/bin/hypr-scroll movewindowto u
bind=$mainMod SHIFT, down, exec, ~/.local/bin/hypr-scroll movewindowto d
bind=$mainMod SHIFT, h, exec, ~/.local/bin/hypr-scroll swapcol l
bind=$mainMod SHIFT, l, exec, ~/.local/bin/hypr-scroll swapcol r
bind=$mainMod SHIFT, k, exec, ~/.local/bin/hypr-scroll movewindowto u
bind=$mainMod SHIFT, j, exec, ~/.local/bin/hypr-scroll movewindowto d

bind=$mainMod, Q, killactive
bind=$mainMod, F, fullscreen, 0
bind=$mainMod, M, exec, ~/.local/bin/hypr-osc maximize-column
bind=$mainMod, C, exec, ~/.local/bin/hypr-scroll togglefit

bind=$mainMod, R, exec, ~/.local/bin/hypr-scroll colresize +conf
bind=$mainMod CTRL, R, exec, ~/.local/bin/hypr-scroll winresize +conf
bind=$mainMod SHIFT, R, exec, ~/.local/bin/hypr-scroll colresize 0.786
bind=$mainMod, 0, exec, ~/.local/bin/hypr-scroll colresize 0.333
bind=$mainMod SHIFT, 0, exec, ~/.local/bin/hypr-scroll colresize 0.500
bind=$mainMod ALT, 0, exec, ~/.local/bin/hypr-scroll colresize 0.667
bind=$mainMod CTRL, 0, exec, ~/.local/bin/hypr-scroll colresize 0.800
bind=$mainMod, minus, exec, ~/.local/bin/hypr-scroll colresize -0.05
bind=$mainMod, equal, exec, ~/.local/bin/hypr-scroll colresize +0.05
bind=$mainMod SHIFT, minus, resizeactive, 0 -50
bind=$mainMod SHIFT, equal, resizeactive, 0 50

bind=ALT, G, exec, ~/.local/bin/hypr-osc maximize-window-to-edges
bind=$mainMod CTRL, W, togglegroup
bind=$mainMod, G, exec, ~/.local/bin/hypr-osc toggle-float
bind=$mainMod CTRL, BackSpace, exec, ~/.local/bin/hypr-osc focus-float-tile
bind=$mainMod, Z, exec, ~/.local/bin/hypr-osc zen
bind=$mainMod, P, exec, ~/.local/bin/hypr-osc pin
bind=$mainMod ALT, O, exec, ~/.local/bin/hypr-expo toggle
bind=$mainMod CTRL, left, exec, ~/.local/bin/hypr-osc consume-or-expel left
bind=$mainMod CTRL, right, exec, ~/.local/bin/hypr-osc consume-or-expel right
bind=$mainMod CTRL, h, exec, ~/.local/bin/hypr-osc consume-or-expel left
bind=$mainMod CTRL, l, exec, ~/.local/bin/hypr-osc consume-or-expel right
bind=$mainMod, O, exec, ~/.local/bin/hypr-osc opacity toggle
bind=$mainMod SHIFT, mouse_down, exec, ~/.local/bin/hypr-osc opacity -0.1
bind=$mainMod SHIFT, mouse_up, exec, ~/.local/bin/hypr-osc opacity +0.1
