# App launcher and utility bindings

bind=ALT, T, exec, uwsm app -a start-kkenp -- ~/.local/bin/start-kkenp
bind=$mainMod ALT, Return, exec, uwsm app -a semsumo-daily -- ~/.local/bin/semsumo-daily
bind=ALT, N, exec, uwsm app -a anotes -- anotes
bind=$mainMod SHIFT, A, exec, ~/.local/bin/hypr-osc arrange-windows
bind=$mainMod, Return, exec, uwsm app -a kitty -- kitty
bind=$mainMod CTRL, Return, exec, ~/.local/bin/osc-ndrop --hypr-hide-special dropdown kitty --class dropdown
bind=ALT, Space, exec, ~/.local/bin/osc-shell ipc call plugin:custom-commands toggle
bind=$mainMod ALT, Space, exec, uwsm app -a rofi-launcher -- ~/.local/bin/rofi-launcher
bind=$mainMod CTRL, F, exec, uwsm app -a nemo -- env GTK_THEME=$gtkTheme nemo
bind=ALT CTRL, F, exec, uwsm app -a yazi -- kitty -e yazi
bind=$mainMod, T, exec, uwsm app -a kitty -- kitty

bind=$mainMod ALT, T, exec, ~/.local/bin/hypr-osc smart-focus kitty
bind=$mainMod ALT, B, exec, ~/.local/bin/hypr-osc smart-focus brave
bind=$mainMod ALT, M, exec, ~/.local/bin/hypr-osc smart-focus spotify
bind=$mainMod ALT, N, exec, ~/.local/bin/hypr-osc smart-focus anotes
bind=$mainMod ALT SHIFT, T, exec, ~/.local/bin/hypr-osc pull-window kitty
bind=$mainMod ALT SHIFT, B, exec, ~/.local/bin/hypr-osc pull-window brave
bind=$mainMod ALT SHIFT, M, exec, ~/.local/bin/hypr-osc pull-window spotify
bind=$mainMod ALT SHIFT, N, exec, ~/.local/bin/hypr-osc pull-window anotes

bind=$mainMod, BackSpace, movetoworkspace, special:scratchpad
bind=ALT, BackSpace, togglespecialworkspace, scratchpad
bind=$mainMod ALT, BackSpace, togglespecialworkspace, scratchpad

bind=ALT, U, exec, ~/.local/bin/osc-media mpv toggle
bind=$mainMod CTRL, Y, exec, ~/.local/bin/mpv-manager play-yt
bind=Alt CTRL, Y, exec, ~/.local/bin/mpv-manager stick
bind=ALT SHIFT, Y, exec, ~/.local/bin/mpv-manager move
bind=$mainMod CTRL, F11, exec, ~/.local/bin/mpv-manager save-yt
bind=$mainMod CTRL, F12, exec, ~/.local/bin/mpv-manager wallpaper
