# Workspace flow and app routing shortcuts

bind=$mainMod CTRL, C, movetoworkspace, empty
bind=$mainMod, Page_Up, exec, ~/.local/bin/hypr-osc window-move workspace prev
bind=$mainMod, Page_Down, exec, ~/.local/bin/hypr-osc window-move workspace next
bind=$mainMod, mouse_down, workspace, e+1
bind=$mainMod, mouse_up, workspace, e-1
bind=$mainMod, mouse_left, exec, ~/.local/bin/hypr-scroll focus l
bind=$mainMod, mouse_right, exec, ~/.local/bin/hypr-scroll focus r
bind=ALT, 1, exec, ~/.local/bin/hypr-osc here Kenp
bind=ALT, 2, exec, ~/.local/bin/hypr-osc here TmuxKenp
bind=ALT, 3, exec, ~/.local/bin/hypr-osc here Ai
bind=ALT, 4, exec, ~/.local/bin/hypr-osc here CompecTA
bind=ALT, 5, exec, ~/.local/bin/hypr-osc here WebCord
bind=ALT, 6, exec, ~/.local/bin/hypr-osc here org.telegram.desktop
bind=ALT, 7, exec, ~/.local/bin/hypr-osc here brave-youtube.com__-Default
bind=ALT, 8, exec, ~/.local/bin/hypr-osc here spotify
bind=ALT, 9, exec, ~/.local/bin/hypr-osc here ferdium
bind=ALT, 0, exec, ~/.local/bin/hypr-osc here all
bind=$mainMod ALT, 0, exec, ~/.local/bin/hypr-osc arrange-windows
